Update master_link-shotner-app.yml

diff --git a/.github/workflows/master_link-shotner-app.yml b/.github/workflows/master_link-shotner-app.yml
--- a/.github/workflows/master_link-shotner-app.yml
+++ b/.github/workflows/master_link-shotner-app.yml
@@ -1,6 +1,3 @@
-# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
-# More GitHub Actions for Azure: https://github.com/Azure/actions
-
 name: Build and deploy Node.js app to Azure Web App - link-shotner-app
 
 on:
@@ -13,7 +10,7 @@ jobs:
   build:
     runs-on: ubuntu-latest
     permissions:
-      contents: read #This is required for actions/checkout
+      contents: read 
 
     steps:
       - uses: actions/checkout@v4
@@ -21,17 +18,22 @@ jobs:
       - name: Set up Node.js version
         uses: actions/setup-node@v3
         with:
-          node-version: '22.x'
+          node-version: '20.x'
 
-      - name: npm install, build, and test
+      - name: Install dependencies
         run: |
           cd server
           npm install
-          npm run build --if-present
-          npm run test --if-present
+
+      - name: Build (if applicable)
+        run: |
+          cd server
+          npm run build || echo "No build step required"
 
       - name: Zip artifact for deployment
-        run: zip release.zip ./* -r
+        run: |
+          cd server
+          zip -r ../release.zip .
 
       - name: Upload artifact for deployment job
         uses: actions/upload-artifact@v4
@@ -46,8 +48,8 @@ jobs:
       name: 'Production'
       url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
     permissions:
-      id-token: write #This is required for requesting the JWT
-      contents: read #This is required for actions/checkout
+      id-token: write 
+      contents: read 
 
     steps:
       - name: Download artifact from build job
@@ -57,13 +59,13 @@ jobs:
 
       - name: Unzip artifact for deployment
         run: unzip release.zip
-      
+
       - name: Login to Azure
         uses: azure/login@v2
         with:
-          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7495D973E7804B50B7C90EE9487B1302 }}
-          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_CF408C2095D14A76A384F1CBFC0ED1A7 }}
-          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_81E2DFB2148745D2A439A8686517D36A }}
+          client-id: ${{ secrets.AZURE_CLIENT_ID }}
+          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
+          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
 
       - name: 'Deploy to Azure Web App'
         id: deploy-to-webapp
@@ -71,5 +73,4 @@ jobs:
         with:
           app-name: 'link-shotner-app'
           slot-name: 'Production'
-          package: .
-          
+          package: release.zip
